# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Math 9 Winter 2025
author: Christopher Davis, Yasmeen Baki, and Luke Smith
logo: ash-vapor.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  exclude_patterns:
    - 'Week?/*.ipynb'
  # - 'Week2/*.ipynb'
  #   - 'Week1/Homework1.ipynb'
  #   - 'Week2/Quiz1-Practice.ipynb'
  #   - 'Week6/Homework5.ipynb'
  #   - 'Week7/Week7-Monday.ipynb'
  #   - 'Week7/Week7-Wednesday.ipynb'
  #   - 'Week8/Homework7.ipynb'
  #   - 'Week8/Week8-Video-notebooks.ipynb'
  #   - 'Proj/StudentProjects/*.ipynb'
  execute_notebooks: 'cache'
  allow_errors: true
  timeout: 200

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ybaki97/Math9-Y24  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
